version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports: [ "2181:2181" ]
    hostname: zookeeper
    networks: [ chapter-jvm ]
  kafka:
    image: wurstmeister/kafka
    command: [ start-kafka.sh ]
    ports: [ "9092:9092" ]
    hostname: kafka
    networks: [ chapter-jvm ]
    environment:
      KAFKA_CREATE_TOPICS: "test-topic:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
  spark:
    image: chapter-jvm-kafka:0.1
    ports:
      - 8080:8080
    networks: [ chapter-jvm ]
  python:
    image: python-kafka
    ports:
      - 80:5000
    networks: [ chapter-jvm ]
    depends_on:
      - zookeeper
      - kafka
networks:
  chapter-jvm: